[package]
name = "tabthedev/vide-utils"
description = "A small utilities for centau/vide"
license = "MIT"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "centau/vide@0.4.1"
observers = "sleitnick/observers@^1.0.0"